version: 1.0.{build}

os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
 - x64

configuration:
  - Debug
  - Release

clone_folder: c:\projects\ctmatch

build:
  parallel: false
  project: c:\projects\ctmatch\%CONFIGURATION%\ctmatch.sln
  verbosity: minimal

before_build:
  - cd c:\projects\ctmatch
  - md %CONFIGURATION%
  - cd %CONFIGURATION%
  - cmake -G"Visual Studio 14 2015 Win64" ..

build_script:
 - cd c:\projects\ctmatch\%CONFIGURATION%
 - msbuild /target:match_test /p:Configuration=%CONFIGURATION%;Platform=%PLATFORM% ctmatch.sln

test_script:
 - cd c:\projects\ctmatch\%CONFIGURATION%
 - cmd: ctest -VV
