version: 1.0.{build}

os: Windows Server 2015

matrix:
  fast_finish: true

platform:
 - x64

configuration:
  - Debug
  - Release

clone_folder: c:\projects\ctmatch

build:
  parallel: false
  project: c:\projects\ctmatch\build\$CONFIGURATION\ctmatch.sln
  verbosity: minimal

before_build:
  - cd c:\projects\ctmatch\$CONFIGURATION
  - md build
  - cd build
  - cmake -G"Visual Studio 14 2015 Win64" ..

build_script:
 - cd c:\projects\ctmatch\build\$CONFIGURATION
 - msbuild /target:match_test /p:Configuration=$CONFIGURATION;Platform=$PLATFORM ctmatch.sln

test_script:
 - cd c:\projects\ctmatch\build\$CONFIGURATION
 - cmd: ctest -VV
