version: 1.0.{build}

os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  #- x64

#configuration:
  #- Debug
  #- Release

clone_folder: c:\projects\ctmatch

build:
  parallel: false
  project: c:\projects\ctmatch\build\ctmatch.sln
  verbosity: minimal

before_build:
  - cd c:\projects\ctmatch
  - md build
  - cd build
  - cmake -G"Visual Studio 14 2015 Win64" ..

build_script:
 - cd c:\projects\ctmatch\build
 - msbuild /target:match_test /p:Configuration=Debug;Platform=x64 ctmatch.sln
 - msbuild /target:match_test /p:Configuration=Release;Platform=x64 ctmatch.sln

test_script:
 - cd c:\projects\ctmatch\build
 - cmd: ctest -C Debug -VV
 - cmd: ctest -C Release -VV
